# Generated by Django 3.1.3 on 2021-11-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoesdata1',
            options={'ordering': ['name'], 'verbose_name': 'Обувь', 'verbose_name_plural': 'Обувь'},
        ),
    ]
