# Generated by Django 3.1.3 on 2021-11-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0002_auto_20211124_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoesdata1',
            name='timeScan',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время сканирования'),
        ),
    ]
