# Generated by Django 3.1.3 on 2021-11-27 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0003_auto_20211124_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('magazineName', models.CharField(max_length=200, verbose_name='Магазин')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('sezon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Обувь',
                'verbose_name_plural': 'Обувь',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShoesPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeScan', models.DateTimeField(auto_now_add=True, verbose_name='Время сканирования')),
                ('priceShoes', models.PositiveIntegerField(verbose_name='Цена')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agregator.shoesdata', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Текущая цена',
                'verbose_name_plural': 'Текущие цены',
            },
        ),
        migrations.DeleteModel(
            name='ShoesData1',
        ),
    ]
